# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JMQRCode', '~> 1.0.2'
  pod 'AFNetworking', '~> 3.2.1'
  # Pods for MyProject

end
